import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
          <header>
            <div className="container mx-auto">
              <h1>Header</h1>
            </div>
          </header>

          <main>{children}</main>

          <footer>
            <div className="container mx-auto">
              <h1>Footer</h1>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
